CREATE TABLESPACE LYCEUM_PORTAL DATAFILE 'LYCEUM_PORTAL.dbf' SIZE 64M REUSE 
　 AUTOEXTEND ON NEXT 1280K 
　 MINIMUM EXTENT 128K 
　 DEFAULT STORAGE ( INITIAL 128K NEXT 128K MINEXTENTS 1 MAXEXTENTS 4096 PCTINCREASE 0);

drop user LYCEUM cascade;

create user LYCEUM identified by oracle default tablespace LYCEUM_PORTAL Temporary TABLESPACE Temp;

grant connect,resource,dba,select any table to LYCEUM;